services:
  app:
    container_name: reader-app
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    image: onionyst/reader:latest
    init: true
    networks:
      - back-tier
      - front-tier
    ports:
      - "127.0.0.1:${APP_PORT}:3000"
    restart: always
  postgres:
    container_name: reader-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:14.4-alpine
    init: true
    networks:
      back-tier:
        aliases:
          - postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: reader_postgres

networks:
  back-tier:
    name: reader_net_back
  front-tier:
    name: reader_net_front
